version: "3.8"  # Лучше указывать версию docker-compose

services:
  postgres:
    image: postgres:latest
    container_name: order-postgres_db
    restart: always
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: erkin
    ports:
      - "5432:5432"  # Пробрасываем порт для PostgreSQL
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Убрал лишний символ "м"

  order-service:
    image: order-service-image  # Замени на свой образ
    container_name: order-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: erkin
      SERVER_PORT: 5432  # Здесь указываем порт, но это не пробрасывание порта
    ports:
      - "5432:5432"  # Правильное пробрасывание порта из контейнера наружу
